#!/usr/bin/env bash
# Configure nginx user to nginx
chmod 777 /etc/nginx/nginx/conf
sed -i '1iuser nginx;' etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
